import { SaleStartUPData } from "../interfaces";

export const data : SaleStartUPData[] = [
    {
        title: "Ilova",
        titleInfo: "O'zini kengaytirishni maqsad qilgan", 
        id: 1,
        companyName: "TruckingCom",
        name: "Abdullo Isoyev",
        kasbi: "dasturchi",
        phone: 931305077,
        email: "uzb@gmail.com",
        telegram: "https://t.me/foragede",
        date: "2025-01-29",
        info: "Sababi: Egasi ushbu sarmoya miqdori bilan marketing tashabbuslarini kengaytirish va kuchaytirishni maqsad qilgan.",
        companyType: "Trucking, Logistic",
        investmentSize: 1000000,
        investmentValyuta: "USD",
        investmentVolume: "Qisman",
        qiziqishi: "Dastur ishlab chiqishga",
        tashkilTopgan: "02/03/2025",
        ishchiSoni: 10,
        reyting: 7,
        status: true,
        locationPreference: "Samarkand, Uzbekistan, Kazakhstan, Tajikistan, Kyrgyzstan", 
        image: "https://cdn.prod.website-files.com/5f70f0246e0318453837c2b9/6451a122b19c7f64d14cc91d_starting%20a%20trucking%20business.webp"
    },
    {
        title: "Turarjoy",
        titleInfo: "Qorasuvdagi katta Supermarket sotiladi", 
        id: 2,
        companyName: "Qorasuv Massiv",
        name: "Abdullo Isoyev",
        kasbi: "sotuvchi",
        phone: 931305077,
        email: "qoarsuv@gmail.com",
        telegram: "https://t.me/foragede",
        date: "2024-12-15",
        info: "Sababi: Egasi ushbu Turarjoyni sotib boshqa biznesni kengaytirish va kuchaytirishni maqsad qilgan.",
        companyType: "Turarjoy, Building",
        investmentSize: 1000000,
        investmentValyuta: "UZS",
        investmentVolume: "To'liq",
        qiziqishi: "Dastur ishlab chiqishga",
        tashkilTopgan: "02/03/2025",
        ishchiSoni: 10,
        reyting: 6,
        status: true,
        locationPreference: "Samarkand, Uzbekistan", 
        image: "https://static.zarnews.uz/crop/6/b/736_736_80_6b7220e75f77d8a61298e17690775a84.jpg?img=self&v=1618559553"
    },
    {
        title: "Turarjoy",
        titleInfo: "Navoi shahridagi PS center Sotiladi", 
        id: 3,
        companyName: "GamingCom",
        name: "Abdullo Isoyev",
        kasbi: "taksist",
        phone: 931305077,
        email: "gaminguz@gmail.com",
        telegram: "https://t.me/foragede",
        date: "2021-09-15",
        info: "Sababi: Egasi o'zini biznesini boshqa joyda ochishni maqsad qilgan.",
        companyType: "Gaming, IT",
        investmentSize: 10000,
        investmentValyuta: "USD",
        investmentVolume: "To'liq",
        qiziqishi: "Dastur ishlab chiqishga",
        tashkilTopgan: "02/03/2025",
        ishchiSoni: 10,
        reyting: 7,
        status: true,
        locationPreference: "Navoiy, Uzbekistan", 
        image: "https://assetsio.gnwcdn.com/ps5_control_centre_4.jpg?width=1200&height=1200&fit=bounds&quality=70&format=jpg&auto=webp"
    },
    {
        title: "Ilova",
        titleInfo: "Sun'iy intellekt va mobil ilovalar bo'yicha kompaniya", 
        id: 4,
        companyName: "MobileAI",
        name: "Abdullo Isoyev",
        kasbi: "taksist",
        phone: 931305077,
        email: "mobbile-ai@gmail.com",
        telegram: "https://t.me/foragede",
        date: "2024-09-15",
        info: "Sababi: Egasi ushbu sarmoya miqdori bilan Ilovani tashabbuslarini kengaytirish va kuchaytirishni maqsad qilgan.",
        companyType: "AI, Mobile, IT",
        investmentSize: 1000000,
        investmentValyuta: "USD",
        investmentVolume: "Qisman",
        qiziqishi: "Dastur ishlab chiqishga",
        tashkilTopgan: "02/03/2025",
        ishchiSoni: 10,
        reyting: 7,
        status: false,
        locationPreference: "Samarkand, Uzbekistan, Kazakhstan, Tajikistan, Kyrgyzstan", 
        image: "https://assets.eweek.com/uploads/2023/09/ew_20230929-best-ai-apps.jpg"
    },
    {
        title: "Ilova",
        titleInfo: "Sun'iy intellekt va mobil ilovalar bo'yicha kompaniya", 
        id: 5,
        companyName: "OvozAI",
        name: "Abdullo Isoyev",
        kasbi: "taksist",
        phone: 931305077,
        email: "mobbile-ai@gmail.com",
        telegram: "https://t.me/foragede",
        date: "2024-09-15",
        info: "Sababi: Egasi ushbu sarmoya miqdori bilan Ilovani tashabbuslarini kengaytirish va kuchaytirishni maqsad qilgan.",
        companyType: "AI, Mobile, IT",
        investmentSize: 1500000,
        investmentValyuta: "USD",
        investmentVolume: "Qisman",
        qiziqishi: "Dastur ishlab chiqishga",
        tashkilTopgan: "02/03/2025",
        ishchiSoni: 10,
        reyting: 7,
        status: true,
        locationPreference: "Samarkand, Uzbekistan, Kazakhstan, Tajikistan, Kyrgyzstan", 
        image: "https://usmsystems.com/wp-content/uploads/2020/08/ai-integrated-Speech-Recognition-apps-1-1.jpg"

    },
    {
        title: "Turarjoy",
        titleInfo: "Jomboyda tikish zavodi qisman sotiladi", 
        id: 6,
        companyName: "Tikish Zavod",
        name: "Abdullo Isoyev",
        kasbi: "taksist",
        phone: 931305077,
        email: "mobbile-ai@gmail.com",
        telegram: "https://t.me/foragede",
        date: "2024-09-15",
        info: "Sababi: Egasi ushbu sarmoya miqdori bilan biznes kengaytirish va kuchaytirishni maqsad qilgan.",
        companyType: "AI, Mobile, IT",
        investmentSize: 1000000,
        investmentValyuta: "USD",
        investmentVolume: "Qisman",
        qiziqishi: "Dastur ishlab chiqishga",
        tashkilTopgan: "02/03/2025",
        ishchiSoni: 10,
        reyting: 7,
        status: true,
        locationPreference: "Samarkand, Uzbekistan, Kazakhstan, Tajikistan, Kyrgyzstan", 
        image: "https://srcyrl.jukkymachine.com/uploads/202234185/fhs6-big-emboridery-area-embroidery-machine00532124168.jpg"

    },
    {
        title: "Ilova",
        titleInfo: "Sun'iy intellekt va mobil ilovalar bo'yicha kompaniya", 
        id: 7,
        companyName: "UzJourney",
        name: "Abdullo Isoyev",
        kasbi: "taksist",
        phone: 931305077,
        email: "mobbile-ai@gmail.com",
        telegram: "https://t.me/foragede",
        date: "2024-09-15",
        info: "Sababi: Egasi ushbu sarmoya miqdori bilan Ilovani tashabbuslarini kengaytirish va kuchaytirishni maqsad qilgan.",
        companyType: "AI, Mobile, IT",
        investmentSize: 1000000,
        investmentValyuta: "USD",
        investmentVolume: "Qisman",
        qiziqishi: "Dastur ishlab chiqishga",
        tashkilTopgan: "02/03/2025",
        ishchiSoni: 10,
        reyting: 7,
        status: true,
        locationPreference: "Samarkand, Uzbekistan, Kazakhstan, Tajikistan, Kyrgyzstan", 
        image: "https://assets.hongkiat.com/uploads/imagine-ai-art-generator/imagine-app.jpg"

    },
]

